name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o user-service ./cmd/user

    - name: Test
      run: go test ./...

    - name: Build Docker image
      run: docker build -t campus-trading/user-service:${{ github.sha }} .

    - name: Push Docker image
      run: docker push campus-trading/user-service:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        namespace: campus-trading
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          campus-trading/user-service:${{ github.sha }}
        kubectl-version: 'latest'