apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: campus-trading
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: campus-trading/user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: postgres-dsn
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: jwt-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"